# Generated by Django 2.0.2 on 2021-03-20 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
    ]
