# Generated by Django 2.0.2 on 2021-03-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210307_1838'),
    ]

    operations = [
    ]
