# Generated by Django 2.0.2 on 2021-03-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210307_1839'),
    ]

    operations = [
    ]
