# Generated by Django 2.0.2 on 2021-03-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210307_1904'),
    ]

    operations = [
    ]
