# Generated by Django 2.0.2 on 2021-03-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210307_1908'),
    ]

    operations = [
    ]
